/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jānis' at '8/19/16 4:57 PM' with Gradle 2.13
 *
 * @author Jānis, @date 8/19/16 4:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
